# Generated by Django 3.0 on 2019-12-04 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'boss',
                'verbose_name_plural': 'bosses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cls', models.CharField(choices=[('DR', 'Druid'), ('HU', 'Hunter'), ('MA', 'Mage'), ('PA', 'Paladin'), ('PR', 'Priest'), ('RO', 'Rogue'), ('SH', 'Shaman'), ('WL', 'Warlock'), ('WR', 'Warrior')], max_length=2)),
                ('race', models.CharField(choices=[('DW', 'Dwarf'), ('GN', 'Gnome'), ('HU', 'Human'), ('NE', 'Night Elf'), ('OR', 'Orc'), ('TA', 'Tauren'), ('TR', 'Troll'), ('UD', 'Undead')], max_length=2)),
                ('guid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(choices=[('P', 'Poor'), ('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary'), ('A', 'Artifact')], max_length=1)),
                ('classicdb_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Zone')),
            ],
            options={
                'ordering': ['zone', 'reset'],
            },
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Boss')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Item')),
                ('raid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Raid')),
            ],
            options={
                'verbose_name': 'loot',
                'verbose_name_plural': 'loot',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(through='project_blood_legion.Loot', to='project_blood_legion.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boss',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Zone'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('characters', models.ManyToManyField(to='project_blood_legion.Character')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Raid')),
            ],
            options={
                'ordering': ['raid', 'name'],
                'unique_together': {('raid', 'name')},
            },
        ),
    ]
