# Generated by Django 3.0 on 2019-12-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boss',
            unique_together={('zone', 'name')},
        ),
    ]
