# Generated by Django 3.0 on 2019-12-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0003_remove_unique_boss_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Character'),
        ),
    ]
