# Generated by Django 3.0 on 2019-12-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0004_remove_loot_require_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'ordering': ['character', 'item'], 'verbose_name': 'loot', 'verbose_name_plural': 'loot'},
        ),
        migrations.AddField(
            model_name='loot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Group'),
        ),
    ]
