# Generated by Django 3.0 on 2019-12-17 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0005_add_group_to_loot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name': 'boss', 'verbose_name_plural': 'bosses'},
        ),
        migrations.AddField(
            model_name='raid',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 22, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raid',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 22, 0, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
