# Generated by Django 3.0 on 2019-12-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0006_add_raid_dates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raid',
            unique_together={('zone', 'reset')},
        ),
    ]
