# Generated by Django 3.0 on 2019-12-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0007_unique_raid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Instance',
        ),
        migrations.RenameField(
            model_name='loot',
            old_name='group',
            new_name='instance',
        ),
    ]
