# Generated by Django 3.0 on 2019-12-21 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0010_create_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['main_character']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['character']},
        ),
        migrations.AddField(
            model_name='instance',
            name='scheduled_start',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 22, 0, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
