# Generated by Django 3.0 on 2019-12-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0011_add_instance_scheduled_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Character')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Member')),
            ],
        ),
    ]
