# Generated by Django 3.0 on 2020-01-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0012_add_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Leader'), (2, 'Officer'), (3, 'Raider'), (4, 'Member'), (5, 'Trial'), (6, 'Friend')], default=3),
            preserve_default=False,
        ),
    ]
