# Generated by Django 3.0.3 on 2020-02-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0014_add_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='classicdb_id',
            new_name='classic_item_id',
        ),
        migrations.AddField(
            model_name='boss',
            name='items',
            field=models.ManyToManyField(db_table='project_blood_legion_boss_items', to='project_blood_legion.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='classicdb_item_id_suffix',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
