# Generated by Django 3.0.3 on 2020-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0015_add_boss_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='items',
            field=models.ManyToManyField(blank=True, db_table='project_blood_legion_boss_items', to='project_blood_legion.Item'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='characters',
            field=models.ManyToManyField(blank=True, to='project_blood_legion.Character'),
        ),
    ]
