# Generated by Django 3.0.4 on 2020-04-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0016_allow_blank_in_boss_and_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['-zone__id', 'id'], 'verbose_name': 'boss', 'verbose_name_plural': 'bosses'},
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Leader'), (2, 'Officer'), (3, 'Raider'), (4, 'Trial'), (5, 'Member'), (6, 'Friend'), (7, 'Retired')]),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Character')),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve1', to='project_blood_legion.Item')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve2', to='project_blood_legion.Item')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Zone')),
            ],
            options={
                'unique_together': {('character', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='InstanceReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Character')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Instance')),
                ('item1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_reserve1', to='project_blood_legion.Item')),
                ('item2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_reserve2', to='project_blood_legion.Item')),
            ],
            options={
                'unique_together': {('character', 'instance')},
            },
        ),
    ]
