# Generated by Django 3.0.4 on 2020-04-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0017_add_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancereserve',
            options={'ordering': ['character', 'instance']},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['character', 'zone']},
        ),
        migrations.AlterField(
            model_name='alt',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alts', to='project_blood_legion.Member'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_blood_legion.Member'),
        ),
        migrations.AlterField(
            model_name='instancereserve',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='project_blood_legion.Instance'),
        ),
    ]
