# Generated by Django 3.0.8 on 2021-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blood_legion', '0019_add_zone_related_name_bosses'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
